spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshop?characterEncoding=UTF-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
